name: Catsbit
description: Дизайнер со времен Wen.ru и Kmx.ru, охочусь за халявой!
dtitle: Дизайнер с халявой 🐱

avatar: https://avatars2.githubusercontent.com/u/31637004?v=4&s=460

footer-links:
  dribbble:
  email:
  vk:
  facebook:
  
disqus:

google_analytics:

url:
baseurl: ""
excerpt_separator: <!--more-->

# Site settings
permalink: pretty

# Pages permalink
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename:output_ext

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
