name: IO:Enso
description: IO:Enso (Enso Okame).<br/>Веб-разработчик / кодер / графический дизайнер 👨‍💻<br/>P.S. «Enso Okame» это всего-лишь псевдоним 🐱
dtitle: Тихий уголок кота-кодера 🐱

avatar: /assets/img/me_1.jpg

footer-links:
  dribbble:
  email:
  vk:
  facebook:
  
disqus:

google_analytics:

url:
baseurl: ""
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title.html

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
