name: Økame (@ioenso)

description: Веб разработчик (☺)

avatar: http://ioenso.github.io/assets/img/avatar.jpg

footer-links:
  dribbble:
  email:
  vk:
  facebook:
  
disqus:

google_analytics:

url:
baseurl: ""
excerpt_separator: <!--more-->
permalink: /:title/

version: v1.2.0

markdown: redcarpet
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
